api:
  base_url: "https://dotnet-ship-hfdfcxh5etb8bgch.westeurope-01.azurewebsites.net"
  endpoint: "management/stats"
  timeout: 10
  team_0: "Rome"
  team_1: "Carthage"
server:
  host: "localhost"
  port: 5555